# In /etc/default/grub
# I changed
# GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
# to this
# GRUB_CMDLINE_LINUX_DEFAULT="quiet splash amdgpu.dcdebugmask=0x10" # This disables Panel Self Refresh because my PC freezes due to AMD GPU bug, deep sleep to avoid an error where my system doesn't get turned on after opending the laptop lid
