# Get this file with:
# comm -23 <(apt-mark showmanual | sort)  <(dpkg --get-selections | grep deinstall | awk '{print $1}' | sort) > my-packages-manual.txt
sudo apt install binutils-dev -y
sudo apt install bison -y
sudo apt install brightnessctl -y
sudo apt install bsdutils -y
sudo apt install build-essential -y
sudo apt install cabal-debian -y
sudo apt install cloudflare-warp -y
sudo apt install code -y
sudo apt install curl -y
sudo apt install dash -y
sudo apt install diffutils -y
sudo apt install docker-compose -y
sudo apt install docker.io -y
sudo apt install efibootmgr -y
sudo apt install findutils -y
sudo apt install flex -y
sudo apt install gh -y
sudo apt install git -y
sudo apt install git-email -y
sudo apt install grep -y
sudo apt install grub-efi-amd64 -y
sudo apt install grub-efi-amd64-signed -y
sudo apt install gzip -y
sudo apt install hasktags -y
sudo apt install hlint -y
sudo apt install hostname -y
sudo apt install htop -y
sudo apt install ibus-table-cangjie3 -y
sudo apt install ibus-table-cangjie5 -y
sudo apt install ibus-table-cangjie-big -y
sudo apt install init -y
sudo apt install language-pack-en -y
sudo apt install language-pack-en-base -y
sudo apt install language-pack-gnome-en -y
sudo apt install language-pack-gnome-en-base -y
sudo apt install libcap-dev -y
sudo apt install libchewing3 -y
sudo apt install libchewing3-data -y
sudo apt install libdw-dev -y
sudo apt install libelf-dev -y
sudo apt install libffi8 -y
sudo apt install libffi-dev -y
sudo apt install libgmp10 -y
sudo apt install libgmp-dev -y
sudo apt install libm17n-0 -y
sudo apt install libmarisa0 -y
sudo apt install libncurses-dev -y
sudo apt install libnuma-dev -y
sudo apt install libopencc1.1 -y
sudo apt install libopencc-data -y
sudo apt install libotf1 -y
sudo apt install libpinyin15 -y
sudo apt install libpinyin-data -y
sudo apt install libpq-dev -y
sudo apt install libssl-dev -y
sudo apt install libunwind-dev -y
sudo apt install libx11-dev -y
sudo apt install libxft-dev -y
sudo apt install libxinerama-dev -y
sudo apt install libxrandr-dev -y
sudo apt install libxss-dev -y
sudo apt install linux-generic-hwe-24.04 -y
sudo apt install linux-modules-nvidia-580-open-generic-hwe-24.04 -y
sudo apt install login -y
sudo apt install m17n-db -y
sudo apt install mesa-utils -y
sudo apt install ncurses-base -y
sudo apt install ncurses-bin -y
sudo apt install nvidia-driver-580-open -y
sudo apt install openssl -y
sudo apt install pkg-config -y
sudo apt install python3-dbus -y
sudo apt install python3-dev -y
sudo apt install python3-netifaces -y
sudo apt install python3-setuptools -y
sudo apt install python3-venv -y
sudo apt install ripgrep -y
sudo apt install shim-signed -y
sudo apt install silversearcher-ag -y
sudo apt install suckless-tools -y
sudo apt install tar -y
sudo apt install tree -y
sudo apt install ubuntu-desktop-minimal -y
sudo apt install ubuntu-minimal -y
sudo apt install ubuntu-standard -y
sudo apt install ubuntu-wallpapers -y
sudo apt install unzip -y
sudo apt install upwork -y
sudo apt install vim -y
sudo apt install vim-gtk3 -y
sudo apt install wpasupplicant -y
sudo apt install x11-utils -y
sudo apt install xmonad -y
sudo apt install zip -y
sudo apt install zlib1g-dev -y
